language: java
jdk:
    - openjdk8
    - oraclejdk8
env:
    - SRC_DIR=SE_module
install: true
script: 
    - git clone https://github.com/clarus-proxy/dataoperations-api.git && cd dataoperations-api && mvn install && cd ..
    - cd $SRC_DIR && mvn install
