#!bin/bash
#################################################################
#		Script for a new VM for SE module		#
#################################################################

#################################################################
# Monir Azraoui							#
# EURECOM							#
# October 30, 2017						#
#								#
# This is a script that lists a set of bash commands to set up	#
# a new Virtual Machine (VM) for the Searchable Encryption (SE)	#
# Module developed in the context of the CLARUS project.	#
#								#
# The script has been tested on a Ubuntu (16.04) machine	#
#								#
# Tested on VMware Workstation 12 Player			#
# The script must be run in SUDO mode.				#
#################################################################


# Measure execution time
start=$(date +%s.%N)

#####
# Update apt-get repo list
#####
echo 'Update apt-get repo list'
apt-get update


#####
# Git
#####
echo 'Install Git'
apt-get install -y git



#####
# Checkout project 
#####
cd ~/Desktop
echo 'Checkout project'
git clone https://gitlab.eurecom.fr/monir.azraoui/SE_module_final
chmod 777 -R SE_module_final/

#####
# C compiler
#####
echo 'Install C compiler'
apt-get install -y g++


#####
# Java
#####
echo 'Install Java'
apt-get install -y openjdk-8-jdk


#####
# Maven
#####
echo 'Install Maven'
apt-get install -y maven

mvn install:install-file -DgroupId=commons-lang -DartifactId=commons-lang -Dversion=2.6 -Dpackaging=jar -Dfile=SE_module_final/classpath/commons-lang-2.6.jar -DgeneratePom=true

#####
# PostgreSQL
#####
echo 'Install PostgreSQL'
apt-get install -y postgresql-common 
apt-get install -y postgresql
apt-get install -y postgresql-server-dev-9.5
apt-get install -y libecpg-dev
apt-get install -y libkrb5-dev


#####
# PL/Java
#####
echo 'Download the latest release of PL/Java'
git clone https://github.com/tada/pljava
chmod 777 pljava/
cd pljava/
echo 'Install PL/Java'
mvn clean install #should check success lines

java -jar pljava-packaging/target/pljava-pg9.5-amd64-Linux-gpp.jar 
# IF ERROR check if the parameters are correct 
# 9.5 is the postgresql version
# amd64 is the architecture of your system
# Linux is the OS

mvn install:install-file -DgroupId=org.postgresql -DartifactId=pljava-api -Dversion=1.6.0-SNAPSHOT -Dpackaging=jar -Dfile=pljava-api/target/pljava-api-1.6.0-SNAPSHOT.jar -DgeneratePom=true
mvn install:install-file -DgroupId=org.postgresql -DartifactId=pljava -Dversion=1.6.0-SNAPSHOT -Dpackaging=jar -Dfile=pljava/target/pljava-1.6.0-SNAPSHOT.jar -DgeneratePom=true

cd ~/Desktop
FILE="'file://"
JARPATH="/Desktop/SE_module_final/JARs/cloud_search_with_SE-1.jar'"
JARPATH=$FILE$HOME$JARPATH
sudo -u postgres createuser "user";
sudo -u postgres psql <<EOF
SET pljava.libjvm_location TO
'/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so';
ALTER DATABASE postgres SET pljava.libjvm_location FROM CURRENT;
CREATE EXTENSION IF NOT EXISTS pljava;
GRANT USAGE ON LANGUAGE java TO PUBLIC;
select sqlj.install_jar($JARPATH, 'search_with_SE', true);
select sqlj.set_classpath('public', 'search_with_SE');
alter user "user" with encrypted password '123';
grant all privileges on database postgres to "user";
grant all privileges on schema sqlj to "user";
\q
EOF





dur=$(echo "$(date +%s.%N) - $start"| bc)
echo "Execution time: ", $dur, " seconds"
echo ""

